[package]
name = "terra_track"
version = "1.0.0"
edition = "2021"


[workspace]
members = [".", "migration", "entity", "service"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }
service = { path = "service" }

tokio = { version = "1", features = ["full"] }
futures = "0"

serde = "1"
serde-xml-rs = "0"
anyhow = "1"
dotenvy = "0"

chrono = "0"
rand = "0"
