[package]
name = "terra-track"
version = "1.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "^0"
anyhow = "^1"
chrono = "^0"
mongodb = "^2"
tokio = { version = "^1", features = ["full"] }
