[package]
name = "terra-track"
version = "1.0.0"
edition = "2021"


[dependencies]
async-std = "1"
futures = "0"
serde = "1"
serde_derive = "1"
anyhow = "1"
nmap_xml_parser = "0"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0"