[package]
name = "terra-track"
version = "1.0.0"
edition = "2021"


[workspace]
members = [".", "migration", "entity"]

[dependencies]
entity = { path = "entity" }
migration = { path = "migration" }

tokio = { version = "1", features = ["full"] }
futures = "0"

serde = "1"
anyhow = "1"
dotenvy = "0"

chrono = "0"
nmap_xml_parser = "0"
rand = "0"
serde-xml-rs = "0.6.0"