version: "3.8"

services:
  terra-track-vpn:
    container_name: terra-track-vpn
    restart: always
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}

  terra-track:
    container_name: terra-track
    restart: always
    build:
      dockerfile: Dockerfile
    volumes:
      - ~/terra-track-output:/app/output


  terra-track-db:
    container_name: terra-track-db
    image: postgres:alpine
    restart: always
    ports:
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST_AUTH_METHOD=trust
