version: "3.8"

services:
  terra-track:
    container_name: terra-track
    restart: always
    network_mode: service:terra-track-vpn
    depends_on:
      - terra-track-db
      - terra-track-vpn
    build:
      dockerfile: Dockerfile
      args:
        - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
    volumes:
      - ~/terra-track-output:/app/output

  terra-track-vpn:
    container_name: terra-track-vpn
    restart: always
    network_mode: bridge
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    environment:
      # - VPN_SERVICE_PROVIDER=mullvad
      # - VPN_TYPE=openvpn
      # - OPENVPN_USER=${OPENVPN_USER}
      # - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=${SERVER_CITIES}
      - LOG_LEVEL=debug
    links:
      - terra-track-db

  terra-track-db:
    container_name: terra-track-db
    image: postgres:alpine
    restart: always
    network_mode: bridge
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
