[package]
name = "scanner"
version = "1.0.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"] }
futures = "0"
serde_path_to_error = "0"
serde = { version = "1", features = ["derive"] }
anyhow = "1"
quickxml_to_serde = "0"
serde_json = "1"
rand = "0"


[dependencies.sea-orm]
version = "0"
features = ["debug-print", "runtime-tokio-rustls", "sqlx-postgres"]
