[package]
name = "rustscan"
version = "1.0.0"
edition = "2021"

[dependencies]
async-std = "1"
futures = "0"
gcd = "2"
rand = "0"
cidr-utils = "0"
itertools = "0"
trust-dns-resolver = { version = "0", features = ["dns-over-rustls"] }
anyhow = "1"
