[package]
name = "api"
version = "1.0.0"
edition = "2021"


[dependencies]
poem = { version = "1" }
sea-orm = { version = "0" }
seaography = { version = "1.0.0-rc.2", features = [
  "with-decimal",
  "with-chrono",
] }
async-graphql = { version = "6", features = [
  "decimal",
  "chrono",
  "dataloader",
  "dynamic-schema",
] }
async-graphql-poem = { version = "6" }
async-trait = { version = "0" }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
dotenv = "0.15.0"

[dev-dependencies]
serde = "1"
serde_json = { version = "1.0.103" }
