//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.6

pub mod prelude;

pub mod ip_flag;
pub mod ip_host_script;
pub mod ip_hosting_details;
pub mod ip_location;
pub mod ip_main;
pub mod ip_network_details;
pub mod ip_organization;
pub mod ip_os;
pub mod ip_security_flags;
pub mod ip_service;
pub mod ip_service_script;
pub mod scan_batch;
