//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.4

pub use super::ip_abuse_contact::Entity as IpAbuseContact;
pub use super::ip_connection::Entity as IpConnection;
pub use super::ip_contact_details::Entity as IpContactDetails;
pub use super::ip_flag::Entity as IpFlag;
pub use super::ip_hosting_details::Entity as IpHostingDetails;
pub use super::ip_location::Entity as IpLocation;
pub use super::ip_main::Entity as IpMain;
pub use super::ip_network_details::Entity as IpNetworkDetails;
pub use super::ip_organization::Entity as IpOrganization;
pub use super::ip_os::Entity as IpOs;
pub use super::ip_privacy::Entity as IpPrivacy;
pub use super::ip_security_flags::Entity as IpSecurityFlags;
pub use super::ip_service::Entity as IpService;
pub use super::ip_service_script::Entity as IpServiceScript;
pub use super::scan_batch::Entity as ScanBatch;
